# Generated by Django 5.0.14 on 2026-05-21 21:28

import django.contrib.auth.models
import django.contrib.auth.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji or icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("student", "Student Freelancer"),
                            ("client", "Client"),
                            ("both", "Both"),
                        ],
                        default="student",
                        max_length=10,
                    ),
                ),
                (
                    "school",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unilag", "University of Lagos (UNILAG)"),
                            ("ui", "University of Ibadan (UI)"),
                            ("oau", "Obafemi Awolowo University (OAU)"),
                            ("uniben", "University of Benin (UNIBEN)"),
                            ("abu", "Ahmadu Bello University (ABU)"),
                            ("unn", "University of Nigeria, Nsukka (UNN)"),
                            ("lautech", "Ladoke Akintola University (LAUTECH)"),
                            ("covenant", "Covenant University"),
                            ("babcock", "Babcock University"),
                            ("futa", "Federal University of Technology, Akure (FUTA)"),
                            ("futo", "Federal University of Technology, Owerri (FUTO)"),
                            ("lasu", "Lagos State University (LASU)"),
                            ("eksu", "Ekiti State University (EKSU)"),
                            ("other", "Other Institution"),
                        ],
                        max_length=50,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=200)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Tell clients about yourself, your skills and experience",
                        max_length=1000,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number with country code (e.g., 2348012345678)",
                        max_length=20,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a professional photo",
                        null=True,
                        upload_to="profiles/",
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available for Work"),
                            ("busy", "Currently Busy"),
                            ("not_available", "Not Available"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                (
                    "verification_doc",
                    models.ImageField(
                        blank=True,
                        help_text="Upload student ID card for verification",
                        null=True,
                        upload_to="verification/",
                    ),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("profile_complete", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dark_mode", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "saved_freelancers",
                    models.ManyToManyField(
                        blank=True, related_name="saved_by", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="accounts.skill"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
